### PR TITLE
Html template

### PR DESCRIPTION
**Pull request by PlasmaIntec**
Implemented individual reviews when Reviews component is fed with fake JSON data

may need to still work on adding buttons for helpfulness and reporting
will add VIP badge if time permits

### CODE REVIEW

**Comment by paul-do** [comment]
Great comments - code is very readable and the initial set-up looks great! @PlasmaIntec

**Comment by PlasmaIntec** [comment]
Wrote E2E tests and ready for PR to be merged

**Comment by PlasmaIntec** [comment]
Requesting merge @paul-do

**Comment by paul-do** [comment]
Only comment I have to make is to re-name your table to describe your data.

Everything else up to this point looks great. Excellent structure and great readability - looks good to merge! @PlasmaIntec

**Pull request merged**
